module github.com/raulcnadal/applivery-soar-agent-macos

go 1.21

// fsnotify — Event Watches' "fsEventsPath" watch type (eventwatch_macos.go,
// macOS parity roadmap Phase 5). kqueue-based on Darwin, pure Go, no CGo —
// keeps this repo's "no local macOS build machine needed, CI (macos-latest)
// verifies it" property intact. go.sum is generated by CI's own `go mod
// tidy` step (build-pkg.yml) rather than hand-authored here — this sandbox
// has no network access to compute the correct checksum-database hashes by
// hand, so go.sum intentionally does not exist yet in this commit.
require github.com/fsnotify/fsnotify v1.7.0